<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elsa.Basic.Flow.Domain\Elsa.Basic.Flow.Domain.csproj" />
    <ProjectReference Include="..\Elsa.Basic.Flow.Services\Elsa.Basic.Flow.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DistributedLock.MongoDB" Version="1.0.0" />
    <PackageReference Include="Elsa.Persistence.MongoDb" Version="3.6.*" />
    <PackageReference Include="Elsa.Scheduling" Version="3.6.*" />
    <PackageReference Include="Elsa.Workflows.Runtime" Version="3.6.*" />
    <PackageReference Include="MongoDB.Driver" Version="3.*" />
  </ItemGroup>

</Project>
